const tabelaTimes = [
    {
        "nome":"Flamengo",
        "grupo":"Único",
        "urlEscudo":new URL('https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flamengo_braz_logo.svg/250px-Flamengo_braz_logo.svg.png'),
        "sigla":"FLA",
        "jogos":11,
        "vitorias":7,
        "empates":2,
        "derrotas":2,
        "golsPro":25,
        "golsContra":5,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Volta Redonda",
        "grupo":"Único",
        "urlEscudo":new URL('https://upload.wikimedia.org/wikipedia/pt/b/ba/Volta%C3%A7oFC.png'),
        "sigla":"VRE",
        "jogos":11,
        "vitorias":6,
        "empates":2,
        "derrotas":3,
        "golsPro":13,
        "golsContra":12,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Fluminense",
        "grupo":"Único",
        "urlEscudo":new URL('https://tntsports.com.br/__export/1588108304121/sites/esporteinterativo/img/2020/04/28/arte_fluminense.png_375107878.png'),
        "sigla":"FLU",
        "jogos":11,
        "vitorias":4,
        "empates":5,
        "derrotas":2,
        "golsPro":13,
        "golsContra":9,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Vasco da Gama",
        "grupo":"Único",
        "urlEscudo":new URL('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrkgZdrbGTJgsEFnQy2u7_9OIH-1DHjaTzUw&s'),
        "sigla":"VG",
        "jogos":11,
        "vitorias":4,
        "empates":5,
        "derrotas":2,
        "golsPro":13,
        "golsContra":9,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Sampaio Corrêa",
        "grupo":"Único",
        "urlEscudo":new URL('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy31Hmhsyc7nLHn7MXt8veJ7yGiTJI977P_w&s'),
        "sigla":"SCF",
        "jogos":11,
        "vitorias":4,
        "empates":4,
        "derrotas":3,
        "golsPro":13,
        "golsContra":11,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Nova Iguaçu",
        "grupo":"Único",
        "urlEscudo":new URL('https://preview.redd.it/66s77v1yxin91.png?width=640&crop=smart&auto=webp&s=331f147141927a4607094099e5cc63e16a52f8ef'),
        "sigla":"NI",
        "jogos":11,
        "vitorias":4,
        "empates":4,
        "derrotas":3,
        "golsPro":8,
        "golsContra":9,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Madureira",
        "grupo":"Único",
        "urlEscudo":new URL('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS7arw_UgM2b3NQbrXfBTNLZtXjns6yz6_LQ&s'),
        "sigla":"EC",
        "jogos":11,
        "vitorias":4,
        "empates":3,
        "derrotas":4,
        "golsPro":11,
        "golsContra":8,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Boavista",
        "grupo":"Único",
        "urlEscudo":new URL('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJLOZ3HD3hCd4igu6mIci2tDA2faX6yEuAWw&s'),
        "sigla":"BOA",
        "jogos":11,
        "vitorias":2,
        "empates":8,
        "derrotas":1,
        "golsPro":10,
        "golsContra":8,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Botafogo",
        "grupo":"Único",
        "urlEscudo":new URL('https://upload.wikimedia.org/wikipedia/commons/c/cb/Escudo_Botafogo.png'),
        "sigla":"BFC",
        "jogos":11,
        "vitorias":4,
        "empates":1,
        "derrotas":6,
        "golsPro":11,
        "golsContra":17,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
       "nome":"Maricá",
        "grupo":"Único",
        "urlEscudo":new URL('https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiEXj_Sy2Mvi48ejARHhIQyxYd2jvY5UAj8uVHEby5NAwvaebbXkFmwC6Zj3vFip5X_s7lixkrJwpIbyNIdsNOBfGuib0ITNQQHK_RVmlfsaxLIQu3qN7HdP6U829R438ALH6Zg5tDBcTeT/s1600/Maric%25C3%25A1+FC-RJ+%2528BRA%2529.png'),
        "sigla":"MFC",
        "vitorias":3,
        "empates":3,
        "derrotas":5,
        "golsPro":11,
        "golsContra":17,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0, 
    },
    {
        "nome":"Portuguesa RJ",
        "grupo":"Único",
        "urlEscudo":new URL('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPTOTWsAbKK7lNl8YGnuXcnFNGSwsAA6QLFw&s'),
        "sigla":"AAP",
        "jogos":11,
        "vitorias":3,
        "empates":1,
        "derrotas":7,
        "golsPro":12,
        "golsContra":24,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
    {
        "nome":"Bangu",
        "grupo":"Único",
        "urlEscudo":new URL('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKt1JXlk67ciRvgr0nJ2UVsBQNrdY1NwOMjA&s'),
        "sigla":"BGU",
        "jogos":11,
        "vitorias":0,
        "empates":4,
        "derrotas":7,
        "golsPro":4,
        "golsContra":20,
        "saldoGols":0,
        "pontos":0,
        "desempenho":0,
    },
]

tabelaTimes.forEach((x)=>{
    x.pontos = (x.vitorias*3)+x.empates
    x.saldoGols = x.golsPro-x.golsContra
    x.desempenho = ((x.pontos/(x.jogos*3))*100).toFixed(2)
})

console.log(tabelaTimes)

module.exports = {tabelaTimes}